Include <sys/stat.h> instead of "struct stat" forward declaration
It causes a build error with MinGW:

      CC       gsf-input.lo
    gsf-input.c:632:1: error: conflicting types for 'gsf_input_set_modtime_from_stat'
     gsf_input_set_modtime_from_stat (GsfInput *input,
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from ../gsf/gsf.h:54:0,
                     from gsf-input.c:24:
    ../gsf/gsf-input-impl.h:67:10: note: previous declaration of 'gsf_input_set_modtime_from_stat' was here
     gboolean gsf_input_set_modtime_from_stat (GsfInput *input,
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Makefile:705: recipe for target 'gsf-input.lo' failed

<sys/stat.h> is enough portable because glib/gstdio.h uses it.